In [1]:
import pandas as pd
df = pd.read_csv ("polaMakan.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Usia                          10000 non-null  int64
 1   Jenis_Kelamin                 10000 non-null  object
 2   IMT                           10000 non-null  object
 3   Frekuensi_Sayur               10000 non-null  int64
 4   Frekuensi_Buah                10000 non-null  int64
 5   Frekuensi_Daging_Merah        10000 non-null  int64
 6   Frekuensi_Makanan_Cepat_Saji  10000 non-null  int64
 7   Frekuensi_Minuman_Bersoda     10000 non-null  int64
 8   Frekuensi_Alkohol             10000 non-null  object
 9   Frekuensi_Kafein              10000 non-null  object
 10  Aktivitas_Fisik               10000 non-null  object
 11  Durasi_Tidur                  10000 non-null  int64
 12  Kebiasaan_Merokok             10000 non-null  object
 13  Tingkat_Stres                 10000 non-null  object
 14  Work_Life_Balance             10000 non-null  object
 15  Riwayat_Penyakit_Keluarga     10000 non-null  object
 16  Status_Ekonomi                10000 non-null  object
 17  Risiko_Diabetes               10000 non-null  int64
 18  Risiko_Hipertensi             10000 non-null  int64
 19  Risiko_Jantung                10000 non-null  int64
 20  Risiko_Obesitas               10000 non-null  int64
dtypes: int64(11), object(10)
memory usage: 1.6+ MB

,Usia,Jenis_Kelamin,IMT,Frekuensi_Sayur,Frekuensi_Buah,Frekuensi_Daging_Merah,Frekuensi_Makanan_Cepat_Saji,Frekuensi_Minuman_Bersoda,Frekuensi_Alkohol,Frekuensi_Kafein,...,Durasi_Tidur,Kebiasaan_Merokok,Tingkat_Stres,Work_Life_Balance,Riwayat_Penyakit_Keluarga,Status_Ekonomi,Risiko_Diabetes,Risiko_Hipertensi,Risiko_Jantung,Risiko_Obesitas
0,26,Perempuan,Obesitas,5,2,6,3,2,Sesekali,Kopi,...,5,Sesekali,Sedang,Buruk,Jantung,Menengah,0,1,0,1
1,35,Laki-laki,Obesitas,5,3,3,4,3,Sering,Kopi,...,5,Sesekali,Rendah,Sedang,Tidak ada,Tinggi,0,1,0,1
2,30,Perempuan,Normal,0,1,2,2,6,Sesekali,Kopi,...,8,Tidak,Rendah,Sedang,Hipertensi,Menengah,0,1,0,0
3,53,Perempuan,Underweight,3,4,3,4,1,Tidak,Kopi,...,4,Sesekali,Sedang,Baik,Diabetes,Menengah,0,0,0,0
4,28,Perempuan,Overweight,2,4,3,0,6,Tidak,Teh,...,4,Sering,Rendah,Sedang,Tidak ada,Tinggi,0,1,0,0

In [2]:
df.isnull().sum()

Usia                            0
Jenis_Kelamin                   0
IMT                             0
Frekuensi_Sayur                 0
Frekuensi_Buah                  0
Frekuensi_Daging_Merah          0
Frekuensi_Makanan_Cepat_Saji    0
Frekuensi_Minuman_Bersoda       0
Frekuensi_Alkohol               0
Frekuensi_Kafein                0
Aktivitas_Fisik                 0
Durasi_Tidur                    0
Kebiasaan_Merokok               0
Tingkat_Stres                   0
Work_Life_Balance               0
Riwayat_Penyakit_Keluarga       0
Status_Ekonomi                  0
Risiko_Diabetes                 0
Risiko_Hipertensi               0
Risiko_Jantung                  0
Risiko_Obesitas                 0
dtype: int64

In [3]:
jumlah_duplikat = df.duplicated().sum()
print(f"Jumlah data duplikat: {jumlah_duplikat}")

Jumlah data duplikat: 0

In [4]:
df_binned = df.copy()

df_binned['Usia_binned'] = pd.cut(df['Usia'], bins=[17, 25, 45, 59, 79], 
                                  labels=['Remaja', 'Dewasa', 'Paruh Baya', 'Lansia'])
df_binned['Frekuensi_Sayur_binned'] = pd.cut(df['Frekuensi_Sayur'], bins=[-1, 0, 2, 4, 6], 
                                             labels=['Sangat Jarang','Jarang', 'Sedang', 'Sering',])
df_binned['Frekuensi_Buah_binned'] = pd.cut(df['Frekuensi_Buah'], bins=[-1, 0, 2, 4, 6], 
                                            labels=['Sangat Jarang','Jarang', 'Sedang', 'Sering',])
df_binned['Frekuensi_Daging_Merah_binned'] = pd.cut(df['Frekuensi_Daging_Merah'], bins=[-1, 0, 2, 4, 6], 
                                                    labels=['Sangat Jarang','Jarang','Sedang','Sering',])
df_binned['Frekuensi_Makanan_Cepat_Saji_binned'] = pd.cut(df['Frekuensi_Makanan_Cepat_Saji'], bins=[-1, 0, 2, 4, 6], 
                                                          labels=['Sangat Jarang','Jarang','Sedang', 'Sering',])
df_binned['Frekuensi_Minuman_Bersoda_binned'] = pd.cut(df['Frekuensi_Minuman_Bersoda'], bins=[-1, 0, 2, 4, 6], 
                                                       labels=['Sangat Jarang','Jarang', 'Sedang', 'Sering',])
df_binned['Durasi_Tidur_binned'] = pd.cut(df['Durasi_Tidur'], bins=[0, 4, 6, 9], labels=['Sangat Pendek', 'Pendek', 'Normal'])

aktivitas_mapping = {
    'Tidak aktif': 'Tidak Aktif',
    '1-2 kali/minggu': 'Sedikit',
    '3-5 kali/minggu': 'Sedang',
    '>5 kali/minggu': 'Banyak',
}
df_binned['Aktivitas_Fisik_binned'] = df['Aktivitas_Fisik'].map(aktivitas_mapping)

In [5]:
df_binned[['Aktivitas_Fisik', 'Aktivitas_Fisik_binned', 'Durasi_Tidur', 'Durasi_Tidur_binned','Usia','Usia_binned']]

,Aktivitas_Fisik,Aktivitas_Fisik_binned,Durasi_Tidur,Durasi_Tidur_binned,Usia,Usia_binned
0,3-5 kali/minggu,Sedang,5,Pendek,26,Dewasa
1,3-5 kali/minggu,Sedang,5,Pendek,35,Dewasa
2,1-2 kali/minggu,Sedikit,8,Normal,30,Dewasa
3,1-2 kali/minggu,Sedikit,4,Sangat Pendek,53,Paruh Baya
4,3-5 kali/minggu,Sedang,4,Sangat Pendek,28,Dewasa
...,...,...,...,...,...,...
9995,3-5 kali/minggu,Sedang,4,Sangat Pendek,44,Dewasa
9996,Tidak aktif,Tidak Aktif,8,Normal,73,Lansia
9997,3-5 kali/minggu,Sedang,5,Pendek,38,Dewasa
9998,1-2 kali/minggu,Sedikit,6,Pendek,46,Paruh Baya
9999,Tidak aktif,Tidak Aktif,9,Normal,46,Paruh Baya

In [6]:
df_binned.columns

Index(['Usia', 'Jenis_Kelamin', 'IMT', 'Frekuensi_Sayur', 'Frekuensi_Buah',
       'Frekuensi_Daging_Merah', 'Frekuensi_Makanan_Cepat_Saji',
       'Frekuensi_Minuman_Bersoda', 'Frekuensi_Alkohol', 'Frekuensi_Kafein',
       'Aktivitas_Fisik', 'Durasi_Tidur', 'Kebiasaan_Merokok', 'Tingkat_Stres',
       'Work_Life_Balance', 'Riwayat_Penyakit_Keluarga', 'Status_Ekonomi',
       'Risiko_Diabetes', 'Risiko_Hipertensi', 'Risiko_Jantung',
       'Risiko_Obesitas', 'Usia_binned', 'Frekuensi_Sayur_binned',
       'Frekuensi_Buah_binned', 'Frekuensi_Daging_Merah_binned',
       'Frekuensi_Makanan_Cepat_Saji_binned',
       'Frekuensi_Minuman_Bersoda_binned', 'Durasi_Tidur_binned',
       'Aktivitas_Fisik_binned'],
      dtype='object')

In [7]:
df_binned = pd.get_dummies(df_binned, columns=[
    'Usia_binned','Jenis_Kelamin', 'IMT', 
    'Riwayat_Penyakit_Keluarga','Frekuensi_Sayur_binned', 
    'Frekuensi_Buah_binned', 'Frekuensi_Daging_Merah_binned',
    'Frekuensi_Makanan_Cepat_Saji_binned','Frekuensi_Minuman_Bersoda_binned',
    'Frekuensi_Alkohol','Frekuensi_Kafein', 'Aktivitas_Fisik_binned', 'Durasi_Tidur_binned',
    'Tingkat_Stres', 'Kebiasaan_Merokok', 'Work_Life_Balance','Status_Ekonomi'], drop_first=False, dtype=int)

In [8]:
df_binned.columns

Index(['Usia', 'Frekuensi_Sayur', 'Frekuensi_Buah', 'Frekuensi_Daging_Merah',
       'Frekuensi_Makanan_Cepat_Saji', 'Frekuensi_Minuman_Bersoda',
       'Aktivitas_Fisik', 'Durasi_Tidur', 'Risiko_Diabetes',
       'Risiko_Hipertensi', 'Risiko_Jantung', 'Risiko_Obesitas',
       'Usia_binned_Remaja', 'Usia_binned_Dewasa', 'Usia_binned_Paruh Baya',
       'Usia_binned_Lansia', 'Jenis_Kelamin_Laki-laki',
       'Jenis_Kelamin_Perempuan', 'IMT_Normal', 'IMT_Obesitas',
       'IMT_Overweight', 'IMT_Underweight',
       'Riwayat_Penyakit_Keluarga_Diabetes',
       'Riwayat_Penyakit_Keluarga_Hipertensi',
       'Riwayat_Penyakit_Keluarga_Jantung',
       'Riwayat_Penyakit_Keluarga_Tidak ada',
       'Frekuensi_Sayur_binned_Sangat Jarang', 'Frekuensi_Sayur_binned_Jarang',
       'Frekuensi_Sayur_binned_Sedang', 'Frekuensi_Sayur_binned_Sering',
       'Frekuensi_Buah_binned_Sangat Jarang', 'Frekuensi_Buah_binned_Jarang',
       'Frekuensi_Buah_binned_Sedang', 'Frekuensi_Buah_binned_Sering',
       'Frekuensi_Daging_Merah_binned_Sangat Jarang',
       'Frekuensi_Daging_Merah_binned_Jarang',
       'Frekuensi_Daging_Merah_binned_Sedang',
       'Frekuensi_Daging_Merah_binned_Sering',
       'Frekuensi_Makanan_Cepat_Saji_binned_Sangat Jarang',
       'Frekuensi_Makanan_Cepat_Saji_binned_Jarang',
       'Frekuensi_Makanan_Cepat_Saji_binned_Sedang',
       'Frekuensi_Makanan_Cepat_Saji_binned_Sering',
       'Frekuensi_Minuman_Bersoda_binned_Sangat Jarang',
       'Frekuensi_Minuman_Bersoda_binned_Jarang',
       'Frekuensi_Minuman_Bersoda_binned_Sedang',
       'Frekuensi_Minuman_Bersoda_binned_Sering', 'Frekuensi_Alkohol_Sering',
       'Frekuensi_Alkohol_Sesekali', 'Frekuensi_Alkohol_Tidak',
       'Frekuensi_Kafein_Kopi', 'Frekuensi_Kafein_Minuman Energi',
       'Frekuensi_Kafein_Teh', 'Frekuensi_Kafein_Tidak',
       'Aktivitas_Fisik_binned_Banyak', 'Aktivitas_Fisik_binned_Sedang',
       'Aktivitas_Fisik_binned_Sedikit', 'Aktivitas_Fisik_binned_Tidak Aktif',
       'Durasi_Tidur_binned_Sangat Pendek', 'Durasi_Tidur_binned_Pendek',
       'Durasi_Tidur_binned_Normal', 'Tingkat_Stres_Rendah',
       'Tingkat_Stres_Sedang', 'Tingkat_Stres_Tinggi',
       'Kebiasaan_Merokok_Sering', 'Kebiasaan_Merokok_Sesekali',
       'Kebiasaan_Merokok_Tidak', 'Work_Life_Balance_Baik',
       'Work_Life_Balance_Buruk', 'Work_Life_Balance_Sedang',
       'Status_Ekonomi_Menengah', 'Status_Ekonomi_Rendah',
       'Status_Ekonomi_Tinggi'],
      dtype='object')

In [9]:
columns_to_drop = [
    'Usia','Jenis_Kelamin', 'IMT', 'Riwayat_Penyakit_Keluarga', 'Frekuensi_Sayur', 
    'Frekuensi_Buah', 'Frekuensi_Daging_Merah', 'Frekuensi_Makanan_Cepat_Saji', 
    'Frekuensi_Minuman_Bersoda', 'Frekuensi_Alkohol', 'Frekuensi_Kafein', 
    'Aktivitas_Fisik', 'Durasi_Tidur', 'Tingkat_Stres', 'Kebiasaan_Merokok', 
    'Work_Life_Balance', 'Status_Ekonomi'
]
df_binned = df_binned.drop(columns=columns_to_drop, errors='ignore')

In [10]:
df_binned.dtypes.value_counts()

int64    64
Name: count, dtype: int64

In [11]:
   df_binned[['Usia_binned_Remaja', 'Usia_binned_Dewasa', 'Usia_binned_Paruh Baya','Usia_binned_Lansia', 'Jenis_Kelamin_Laki-laki',
           'Jenis_Kelamin_Perempuan']].head()

,Usia_binned_Remaja,Usia_binned_Dewasa,Usia_binned_Paruh Baya,Usia_binned_Lansia,Jenis_Kelamin_Laki-laki,Jenis_Kelamin_Perempuan
0,0,1,0,0,0,1
1,0,1,0,0,1,0
2,0,1,0,0,0,1
3,0,0,1,0,0,1
4,0,1,0,0,0,1

In [12]:
df_binned.columns = df_binned.columns.str.replace('_binned_', '_', regex=False)

In [13]:

rename_dict = {
    'Risiko_Diabetes': 'RD','Risiko_Hipertensi': 'RH','Risiko_Jantung': 'RJ','Risiko_Obesitas': 'RO',
    'Usia_Remaja': 'A1','Usia_Dewasa': 'A2','Usia_Paruh Baya': 'A3','Usia_Lansia': 'A4',
    'Jenis_Kelamin_Laki-laki': 'B1','Jenis_Kelamin_Perempuan': 'B2',
    'IMT_Normal': 'C1','IMT_Obesitas': 'C2','IMT_Overweight': 'C3','IMT_Underweight': 'C4',
    'Riwayat_Penyakit_Keluarga_Diabetes': 'D1','Riwayat_Penyakit_Keluarga_Hipertensi': 'D2',
    'Riwayat_Penyakit_Keluarga_Jantung': 'D3','Riwayat_Penyakit_Keluarga_Tidak ada': 'D4',
    'Frekuensi_Sayur_Sangat Jarang': 'E1','Frekuensi_Sayur_Jarang': 'E2','Frekuensi_Sayur_Sedang': 'E3','Frekuensi_Sayur_Sering': 'E4',
    'Frekuensi_Buah_Sangat Jarang': 'F1','Frekuensi_Buah_Jarang': 'F2','Frekuensi_Buah_Sedang': 'F3','Frekuensi_Buah_Sering': 'F4',
    'Frekuensi_Daging_Merah_Sangat Jarang': 'G1','Frekuensi_Daging_Merah_Jarang': 'G2',
    'Frekuensi_Daging_Merah_Sedang': 'G3', 'Frekuensi_Daging_Merah_Sering': 'G4',
    'Frekuensi_Makanan_Cepat_Saji_Sangat Jarang': 'H1','Frekuensi_Makanan_Cepat_Saji_Jarang': 'H2',
    'Frekuensi_Makanan_Cepat_Saji_Sedang': 'H3','Frekuensi_Makanan_Cepat_Saji_Sering': 'H4',
    'Frekuensi_Minuman_Bersoda_Sangat Jarang': 'I1','Frekuensi_Minuman_Bersoda_Jarang': 'I2',
    'Frekuensi_Minuman_Bersoda_Sedang': 'I3','Frekuensi_Minuman_Bersoda_Sering': 'I4',
    'Frekuensi_Alkohol_Sering': 'J1','Frekuensi_Alkohol_Sesekali': 'J2','Frekuensi_Alkohol_Tidak': 'J3',
    'Frekuensi_Kafein_Kopi': 'K1','Frekuensi_Kafein_Minuman Energi': 'K2','Frekuensi_Kafein_Teh': 'K3','Frekuensi_Kafein_Tidak': 'K4',
    'Aktivitas_Fisik_Banyak': 'L1','Aktivitas_Fisik_Sedang': 'L2','Aktivitas_Fisik_Sedikit': 'L3','Aktivitas_Fisik_Tidak Aktif': 'L4',
    'Durasi_Tidur_Sangat Pendek': 'M1','Durasi_Tidur_Pendek': 'M2','Durasi_Tidur_Normal': 'M3',
    'Tingkat_Stres_Rendah': 'N1','Tingkat_Stres_Sedang': 'N2','Tingkat_Stres_Tinggi': 'N3',
    'Kebiasaan_Merokok_Sering': 'O1','Kebiasaan_Merokok_Sesekali': 'O2','Kebiasaan_Merokok_Tidak': 'O3',
    'Work_Life_Balance_Baik': 'P1','Work_Life_Balance_Buruk': 'P2','Work_Life_Balance_Sedang': 'P3',
    'Status_Ekonomi_Menengah': 'Q1','Status_Ekonomi_Rendah': 'Q2','Status_Ekonomi_Tinggi': 'Q3'
}

df_binned.rename(columns=rename_dict, inplace=True)

In [14]:
df_binned.columns

Index(['RD', 'RH', 'RJ', 'RO', 'A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'C1', 'C2',
       'C3', 'C4', 'D1', 'D2', 'D3', 'D4', 'E1', 'E2', 'E3', 'E4', 'F1', 'F2',
       'F3', 'F4', 'G1', 'G2', 'G3', 'G4', 'H1', 'H2', 'H3', 'H4', 'I1', 'I2',
       'I3', 'I4', 'J1', 'J2', 'J3', 'K1', 'K2', 'K3', 'K4', 'L1', 'L2', 'L3',
       'L4', 'M1', 'M2', 'M3', 'N1', 'N2', 'N3', 'O1', 'O2', 'O3', 'P1', 'P2',
       'P3', 'Q1', 'Q2', 'Q3'],
      dtype='object')

In [15]:
df_binned.to_csv("dataset_preprocessing.csv", index=False)